### ISSUE TITLE
twamp not working over internet

### ISSUE THREAD

**Issue by subhamxtrades** [demirten/twamp-gui#15]
Hi @all

I Setup Client in Public IP xx.xxx.xx.xx  and enable the port forwarding on that IP, And I setup the responder on different IP xx.xx.xx.xx.

When I am trying to establish the connection TCP handshake is happen after that UDP packets are not going, it show error "No response receive". 
![image](https://user-images.githubusercontent.com/26436242/88278342-d45fdb00-ccff-11ea-9559-80586f2337b9.png)

**Comment by demirten** [comment]
Twamp is not a NAT friendly protocol. It is not enough to create port forwarding rules for just the control protocol (TCP: 862). In the handshake process a new random UDP port selected for the test messages, you should forward this udp ports too.
