### ISSUE TITLE
Twamp client cannot get test message from twamp responder setup in public ip azure virture mahcine

### ISSUE THREAD

**Issue by MightyChee** [demirten/twamp-gui#16]
Hi,

I am using the apk version of twamp client (phone with LTE 4G network) and try to test with twamp responder that setup in a public ip azure virture machine. Everytime i run i get the following result from the client app:

**twamp mobile client**
![image](https://user-images.githubusercontent.com/19426044/96671414-3d54fe80-1394-11eb-89ab-be3b5d82d146.png)

**twamp responder**
![image](https://user-images.githubusercontent.com/19426044/96671027-6fb22c00-1393-11eb-9828-6ad34e2c89b5.png)

**pcap in azure server**
![image](https://user-images.githubusercontent.com/19426044/96671709-0d5a2b00-1395-11eb-9f16-684a032525ce.png)

**full pcap file in azure server**
[twamp-20201021.zip](https://github.com/demirten/twamp-gui/files/5413187/twamp-20201021.zip)

**May i know how can i resolve this situation?**

**Thank you**

**Comment by demirten** [comment]
Twamp is not a NAT friendly protocol. In this case your client and server handshaked with port 40000 but it is translated by the gateway to something else.

You can try with twamp-light which doesn't have twamp tcp control handshake and it is easier for NAT traversal.
