### ISSUE TITLE
Responder Seems to leak memory

### ISSUE THREAD

**Issue by mikeshev** [demirten/twamp-gui#19]
From email exchange:
mikeshev says:
The program seems to be leaking a significant amount of memory. After leaving TWAMP Responder up for about a day (on windows) it leaks about 500M of memory. If I clear logs or restart the process the memory goes back down to about 20MB (measured by windows Task Manager). Do you know of any fix for this? I do not have a Qt5 development environment,

Your Reply:
If GUI is not a problem for you, you can remove the pushing logs to the QT/QML interface. You can open an issue on github project, I can have a look at it if I can found a free time for this.

mikeshev:
 I don't care that responses are shown in the GUI. At this point I'm more interested in have the program run for a longer period of time (at least 1 month - after which I reboot the Windows machine for patches anyways).

**Comment by demirten** [comment]
It is fixed on v1.0.8

Twamp responder not intended to be run for a long time, it can be used in basic client - responder tests. Now, if "Collect Logs" not enabled on responder start, received test packets will not be added into the qml viewer and memory usage remain low.

**Comment by mikeshev** [comment]
Very Nice! I appreciate the extra effort as this was causing my VM to run out of memory and crash about once every 4 days.
