### ISSUE TITLE
fraction part pf timestamp is no accurate

### ISSUE THREAD

**Issue by shabiuri** [demirten/twamp-gui#2]
Fraction part of the time is not accurate as you take the time in milisec and multiply or divide by 4294.967296 which results in values 0-4,294,967 (multiply) or values > 1000 when dividing which is not the full 0-2^32 range nor mili values > 1000

My suggestion is to change:
# define TWAMP_FLOAT_DENOM 4294967.296

Additionally in twamp_time TwampCommon::getTwampTime there are 2 calls to QDateTime::currentMSecsSinceEpoch(), as time changes between calls, I propose to make a single call

the suggestion is as follows:
struct twamp_time TwampCommon::getTwampTime()
{
    struct twamp_time t;
    qint64 tmp_time = QDateTime::currentMSecsSinceEpoch();
    t.seconds = tmp_time / 1000 + TWAMP_BASE_TIME_OFFSET;
    t.fraction = (tmp_time % 1000) \* TWAMP_FLOAT_DENOM;
    return t;
}

**Comment by demirten** [comment]
Before multiplication, modulo(1000) value used so max value can be 4294967 which is less than of unsigned int limit (4294967295)

When it comes to divide operations, if data comes from a buggy client, it is possible to get msecs greater than 1000, so I'll try to add some controls.

I'll also make improvements on twamp_time()

Thanks for your feedback.

**Comment by shabiuri** [comment]
the problem is not the modulo, when you take a millisecond value from the system time and convert it to TWAMP time, the fraction part should be in the range of 0-2^32, this means your need to multiply the millisecond value by 4294967.296

**Comment by demirten** [comment]
Fixed on commit 000fa2d48b97af0309a7c6ea7136ea86d41532ee

I don't changed TWAMP_FLOAT_DENOM definition because it is already used by some other parts in code. It should be ok now.

Thanks for your feedback
