### ISSUE TITLE
no response from server

### ISSUE THREAD

**Issue by pinggit** [demirten/twamp-gui#3]
I installed the windows client and did a quick test on our routers.

and I got this: 

![image](https://cloud.githubusercontent.com/assets/2038044/12928165/f26d6914-cf39-11e5-8709-f3e6e6eed0dc.png)

it looks the initial handshakes are fine but then there is no response to the pull.
I couldn't find any logs from the server, so wondering where is the issue...

**Comment by demirten** [comment]
Is it possible to capture traffic flow with wireshark and attach pcap file here?

**Comment by pinggit** [comment]
hi demirten:

I have the pcap, it just shows probe packets were sent to port 40000 and is rejected by the router (Juniper MX). 
it looks the router is expecting some other port number , so far I know 10000 is fine.
wondering is it OK to provide a custom port number in the GUI?

[twamp-test.zip](https://github.com/demirten/twamp-gui/files/124763/twamp-test.zip)

thanks.

**Comment by demirten** [comment]
When I look at the capture file, it seems that client request udp port 40000 and server (juniper) accepts that port.

If you don't have any firewall between client and server which rejects udp packets, there are two possible scenarios:
1. Juniper twamp responder needs some time to prepare udp ports for the test session
2. System clock of the juniper system back from your PC and juniper twamp responder don't wait for test packets until accepted start time on twamp control handshake session

To find the exact problem, please try followings and send capture file again:
- Start a twamp test with total of 100 packets and 500 miliseconds interval, so it gives failry enough time to juniper side to prepare twamp responder for test packets
- Synchronize both of the PC and juniper clocks from same NTP source
