### ISSUE TITLE
responder padding handling not according to spec in reflected TWAMP-Test messages

### ISSUE THREAD

**Issue by savitski** [demirten/twamp-gui#5]
According to RFC5357 the padding handling with TWAMP-Test messages should be:
Note that the Session-Reflector Test packet formats are larger than the Sender's formats.  The Session-Reflector SHOULD reduce the length of the Sender's Packet Padding to achieve equal IP packet payload lengths in each direction of transmission, when sufficient padding is present.  The Session-Reflector MAY re-use the Sender's Packet Padding (since the requirements for padding generation are the same for each), and in this case the Session-Reflector SHOULD truncate the padding such that the highest-number octets are discarded.

To achieve this change line 368 in twamp_responder_worker.cpp to:

```
int payload = 0;
if (rc > (int)sizeof(struct twamp_message_reflector_unathenticated))
    payload = rc - (int)sizeof(struct twamp_message_reflector_unathenticated);
```

**Comment by demirten** [comment]
Fixed on commit 4481d952399b80575ee432bf53953502afcf8259

Thanks for your feedback
